export const windDirection = {
  N: 'cевер',
  NNE: 'северо-северо-восток',
  NE: 'северо-восток',
  ENE: 'восток-северо-восток',
  E: 'восток',
  ESE: 'восток-юго-восток',
  SE: 'юго-восток',
  SSE: 'юго-юго-восток',
  S: 'юг',
  SSW: 'юго-юго-запад',
  SW: 'юго-запад',
  WSW: 'запад-юго-запад',
  W: 'запад',
  NWN: 'запад-северо-запад',
  NW: 'северо-запад',
  NNW: 'северо-северо-запад',
};

export const windDirectionEng = {
  N: 'North',
  NNE: 'North-North-East',
  NE: 'North-East',
  ENE: 'East-North-East',
  E: 'East',
  ESE: 'East-South-East',
  SE: 'South-East',
  SSE: 'South-South-East',
  S: 'South',
  SSW: 'South-South-West',
  SW: 'South-West',
  WSW: 'West-South-West',
  W: 'West',
  NWN: 'West-North-West',
  NW: 'North-West',
  NNW: 'North-North-West',
};